### Задание 1
Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.
Вычислите, по возможности не используя программирование: (5Е)–1, где Е – единичная матрица размера 5х5.


In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [3]:
c = a + b
c

array([ 6,  8, 10, 12])

In [4]:
d = a - b
d

array([-4, -4, -4, -4])

In [5]:
np.dot(a,b)

70

$(5Е)–1 = 1/5E$

$(5E)-1 = \begin{pmatrix}
     0.2 & 0 & 0 & 0 & 0  \\
     0 & 0.2 & 0 & 0 & 0  \\
     0 & 0 & 0.2 & 0 & 0  \\
     0 & 0 & 0 & 0.2 & 0  \\
     0 & 0 & 0 & 0 & 0.2  \\
    \end{pmatrix}$

### Задание 2
Вычислите определитель:

$det\begin{pmatrix}
     1 & 2 & 3     \\
     4 & 0 & 6     \\
     7 & 8 & 9  \\
\end{pmatrix} = 1*(0*9-6*8) - 2*(4*9-6*7) + 3*(4*8-0*7) = -48 + 12 + 96 =  60 $

In [6]:
# Проверка
np.linalg.det(np.array([1,2,3,4,0,6,7,8,9]).reshape(3,3))

59.999999999999986

### Задание 3
Вычислите матрицу, обратную данной:

Исходнвя матрица

$A = \begin{pmatrix}
     1 & 2 & 3     \\
     4 & 0 & 6     \\
     7 & 8 & 9  \\
    \end{pmatrix}$

Матрица алгебраических дополнений

$A_* = \begin{pmatrix}
     -48 & 6 & 32     \\
     6 & -12 & 6     \\
     12 & 6 & -8  \\
    \end{pmatrix}$

$A _*t = \begin{pmatrix}
     -48 & 6 & 12     \\
     6 & -12 & 6     \\
     32 & 6 & -8  \\
    \end{pmatrix}$

$A_{-1} =A_{*t} / det(A)= \begin{pmatrix}
     -4/5 & 1/10 & 1/5     \\
     1/10 & -1/5 & 1/10     \\
     8/15 & 1/10 & -2/15  \\
    \end{pmatrix}$

Проверка

In [7]:
A_1 = np.array([-4/5,1/10,1/5,1/10,-1/5,1/10,8/15,1/10,-2/15]).reshape(3,3)
A_1

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

In [8]:
A = np.array([1,2,3,4,0,6,7,8,9]).reshape(3,3)
np.linalg.inv(A)

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

Верно!

### Задание 4
Приведите пример матрицы 4х4, ранг которой равен 1.

In [9]:
A = np.array([1,2,3,4,2,4,6,8,4,8,12,16,8,16,24,32]).reshape(4,4)

In [10]:
A

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 4,  8, 12, 16],
       [ 8, 16, 24, 32]])

In [11]:
np.linalg.matrix_rank(A, 0000.1)

1

### Задание 5
Вычислите скалярное произведение двух векторов:  (1, 5)  и  (2, 8)


$\begin{pmatrix}
     1      \\
     5     \\
    \end{pmatrix} 
    \cdot
    \begin{pmatrix}
     2      \\
     8    \\
    \end{pmatrix} = 1*2+5*8=42$

In [12]:
a = np.array([1,5])
b = np.array([2,8])

In [13]:
np.inner(a,b)

42

### Задание 6
Вычислите смешанное произведение трех векторов:
(1, 5, 0), (2, 8, 7) и (7, 1.5, 3) 


$(a \times b) \cdot c = det
    \begin{vmatrix}
     1 & 5 & 0     \\
     2 & 8 & 7     \\
     7 & 1.5 & 3  \\
    \end{vmatrix} =
    1*(8*3-7*1.5) - 5*(2*3-7*7) + 0*(2*1.5-7*8) = 13.5 + 215 + 0 =  228.5 $

In [14]:
a = np.array([1,5,0])
b = np.array([2,8,7])
c = np.array([7,1.5,3])

In [15]:
np.inner(np.cross(a,b),c)

228.5